default/urls.py
from django.urls import path
from .views import *

urlpatterns = [
  # path('poll/',views.poll_list),
   path('poll2/', PollList.as_view()),
   path('poll/<int:pk>/', PollDetail.as_view()),
   path('option/<int:oid>',Pollvote.as_view()),
]

poll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('default.urls')),
]

default/models.py
from django.db import models

# Create your models here.
class Poll(models.Model):
    suject = models.CharField(max_length=200)
    description = models.TextField()
    date_created = models.DateField(auto_now_add =True)

    def __str__(self):
        return str(self.id) + ") " + self.suject
    
class Option(models.Model):
    poll_id = models.IntegerField()
    title = models.CharField(max_length=200)
    count = models.IntegerField(default=0)

default/views.py
from django.shortcuts import render
from .models import Poll, Option
from django.views.generic import ListView, DetailView

# Create your views here.
#def poll_list(req):
#    polls = models.Poll.objects.all()
#    return render(req, 'poll_list.html', {'poll_list': polls})

class PollList(ListView):
    model = Poll

class PollDetail(DetailView):
    model = Poll

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        options = Option.Objects.filter(poll_id=self.kwargs['pk'])
        ctx['options_list'] = options
        return ctx

class PollVote(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        option = Option.objects.get(id=self,kwargs['oid'])
        option.count += 1   # option.count + 1
        option.save()
        return '/poll/' .format(option.poll_id)
        # return '/poll/'+str(option.poll_id)+'/'

default/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>線上投票{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    1234456767
    {% endblock %}    
</body>
</html>

default/templates/default/poll_detail.html
{% extends "base.html" %}}

{% block content %}
<h1>{{ pol.subject }}</h1>  
<p>{{ poll.description }}</p>
<p>建立日期：{{ poll.description_created }}</p>

<ul>
    {% for option in option_list %}
  <li>
      <a href="/option/{{ option.id }}/">{{option.title}}</a>
       - {{ option.count }}票</li>
{% endfor %}
</ul>
{% endblock %}

default/templates/default/poll_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>投票主題</h1>
    <ul>
        {% for poll in poll_list %}
        <li>{{ poll.date_created }} - {{ poll.suject }}</li>  
        {% endfor %}
    </ul>
</body>
</html>

default/templates/poll_list.html
{% extends "base.html" %}

{% block content %}
<h1>投票主題 - ListView</h1>
<ul>
    {% for poll in poll_list %}
    <li>
        {{ poll.date_created }} -
        <a href="/poll/{{ poll.id }}/">{{ poll.suject }}</a>
    </li>  
    {% endfor %}
</ul>  
{% endblock %}

{% block title1111 %}
投票主題列表
{% endblock %}